In [20]:
import pandas as pd


df = pd.read_csv("../raw_data/all_data_batch1_30to60k.csv")

df.head()

,title,release_date,plays,playing,backlogs,wishlist,developers,avg_review,genres,platforms,...,ratings_one_five,ratings_two_zero,ratings_two_five,ratings_three_zero,ratings_three_five,ratings_four_zero,ratings_four_five,ratings_five_zero,image,url
0,Soul Axiom Rebooted,2020-02-27,0,0,4,2,['Wales Interactive'],0.0,"['Adventure', 'Indie', 'Puzzle']","['Windows PC', 'Mac', 'Nintendo Switch']",...,0,0,0,0,0,0,0,0,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/soul-axiom-reb...
1,Panic Station VR,2020-02-27,1,0,0,0,[],0.0,['Indie'],['Windows PC'],...,0,0,0,0,0,0,0,0,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/panic-station-vr/
2,LoveR Kiss,2020-02-27,0,0,0,2,['Kadokawa Games'],0.0,"['Adventure', 'Visual Novel']","['PlayStation 4', 'Nintendo Switch']",...,0,0,0,0,0,0,0,0,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/lover-kiss/
3,Boxman's Struggle,2020-02-27,1,0,1,1,['OneBlock'],0.0,"['Adventure', 'Indie', 'Platform']",['Windows PC'],...,0,0,0,0,0,0,0,0,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/boxmans-struggle/
4,Kemono Heroes,2020-02-27,7,0,6,3,"['NIS America', 'MadGearGames']",3.0,"['Adventure', 'Indie', 'Platform']","['Nintendo Switch', 'Google Stadia']",...,0,1,1,1,0,0,1,0,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/kemono-heroes/

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29959 entries, 0 to 29958
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               29959 non-null  object
 1   release_date        29959 non-null  object
 2   plays               29959 non-null  object
 3   playing             29959 non-null  object
 4   backlogs            29959 non-null  object
 5   wishlist            29959 non-null  object
 6   developers          29959 non-null  object
 7   avg_review          29959 non-null  float64
 8   genres              29959 non-null  object
 9   platforms           29959 non-null  object
 10  description         29134 non-null  object
 11  total_reviews       29959 non-null  object
 12  total_lists         29959 non-null  object
 13  category            29959 non-null  object
 14  main                29959 non-null  object
 15  ratings_zero_five   29959 non-null  int64
 16  ratings_one_zero    29959 non-null  int64
 17  ratings_one_five    29959 non-null  int64
 18  ratings_two_zero    29959 non-null  int64
 19  ratings_two_five    29959 non-null  int64
 20  ratings_three_zero  29959 non-null  int64
 21  ratings_three_five  29959 non-null  int64
 22  ratings_four_zero   29959 non-null  int64
 23  ratings_four_five   29959 non-null  int64
 24  ratings_five_zero   29959 non-null  int64
 25  image               26065 non-null  object
 26  url                 29959 non-null  object
dtypes: float64(1), int64(10), object(16)
memory usage: 6.2+ MB

In [22]:
df = df.sort_values(by=['plays'], ascending = False)

In [23]:
df.head(5)

,title,release_date,plays,playing,backlogs,wishlist,developers,avg_review,genres,platforms,...,ratings_one_five,ratings_two_zero,ratings_two_five,ratings_three_zero,ratings_three_five,ratings_four_zero,ratings_four_five,ratings_five_zero,image,url
24077,Dishonored 2,2016-11-11,9K,280,4.7K,1.3K,"['Arkane Studios', 'Bethesda Softworks']",4.0,"['Adventure', 'RPG', 'Shooter']","['Windows PC', 'PlayStation 4', 'Xbox One']",...,28,94,164,501,917,1841,1061,809,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/dishonored-2/
13424,Lobotomy Corporation,2018-04-09,995,207,801,465,['Project Moon'],4.0,"['Indie', 'Simulator']",['Windows PC'],...,14,14,16,57,71,143,124,185,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/lobotomy-corpo...
25423,Curious Expedition,2016-09-02,99,0,66,17,"['Thunderful', 'Maschinen-Mensch']",3.2,"['Adventure', 'Card & Board Game', 'Indie', 'R...","['Windows PC', 'Mac', 'Linux', 'PlayStation 4'...",...,0,4,10,20,22,7,3,1,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/curious-expedi...
25738,Bowmasters,2016-08-17,99,0,3,2,"['Miniclip.com', 'Playgendary']",2.4,"['Arcade', 'Shooter', 'Turn Based Strategy']","['Android', 'iOS']",...,4,14,11,15,5,2,1,0,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/bowmasters/
9113,Storm Boy,2018-11-20,99,0,19,9,"['Blowfish Studios', 'Level 77 Pty Ltd']",2.5,"['Adventure', 'Indie']","['Windows PC', 'Android', 'Mac', 'PlayStation ...",...,8,18,10,16,8,5,1,3,https://images.igdb.com/igdb/image/upload/t_co...,https://www.backloggd.com/games/storm-boy/

In [27]:
def remove_K_and_fullstop(x):
    if 'K' in x and '.' in x:
        x = x.replace('K', '00')
        x = x.replace('.','')
        return x
    else:
        return x

def remove_K(x):
    if 'K' in x:
        return x.replace('K','000')
    else:
        return x

def objects_reformatted(df, column):
    df[column] = df[column].apply(remove_K_and_fullstop)
    df[column] = df[column].apply(remove_K)
    df[column] = df[column].astype('int')
    return df

In [28]:
numeric_columns = ['plays','playing','backlogs','wishlist','total_reviews','total_lists']

In [29]:
for x in numeric_columns:
    objects_reformatted(df, x)

In [19]:
df[['title','plays','total_reviews','total_lists']].sort_values(by='plays',ascending=False).head(20)

,title,plays,total_reviews,total_lists
21573,The Legend of Zelda: Breath of the Wild,42000,3800,5800
8759,Super Smash Bros. Ultimate,34000,2200,3200
12119,Among Us,34000,3000,1100
16811,Super Mario Odyssey,34000,2400,3900
21775,Hollow Knight,30000,2700,3900
21732,Hollow Knight,30000,2700,3900
8774,Hades,30000,2500,3600
28296,Stardew Valley,29000,1700,2300
14927,Celeste,28000,2400,3700
20388,Mario Kart 8 Deluxe,26000,1300,2000
27032,Overwatch,26000,1500,1200
27956,Dark Souls III,26000,1800,3100
17450,Cuphead,25000,1700,2400
18922,Fortnite,25000,1800,1100
27151,Doom,25000,1400,2300
21809,NieR: Automata,23000,1700,3600
7704,Resident Evil 2,22000,1600,3600
29676,Fallout 4,21000,1100,1400
25239,Persona 5,20000,1400,2200
2336,Star Wars Jedi: Fallen Order,20000,1500,2000

In [ ]:
def remove_K_and_fullstop(x):
    if 'K' in x and '.' in x:
        x = x.replace('K', '00')
        x = x.replace('.','')
        return x
    else: 
        return x

def remove_K(x):
    if 'K' in x:
        return x.replace('K','000')
    else:
        return x

In [ ]:
df['plays'] = df['plays'].apply(remove_K_and_fullstop)
df['playing'] = df['playing'].apply(remove_K_and_fullstop)
df['backlogs'] = df['backlogs'].apply(remove_K_and_fullstop)
df['wishlist'] = df['wishlist'].apply(remove_K_and_fullstop)
df['total_reviews'] = df['total_reviews'].apply(remove_K_and_fullstop)
df['total_lists'] = df['total_lists'].apply(remove_K_and_fullstop)

df['plays'] = df['plays'].apply(remove_K)
df['playing'] = df['playing'].apply(remove_K)
df['backlogs'] = df['backlogs'].apply(remove_K)
df['wishlist'] = df['wishlist'].apply(remove_K)
df['total_reviews'] = df['total_reviews'].apply(remove_K)
df['total_lists'] = df['total_lists'].apply(remove_K)

df['plays'] = df['plays'].astype('int')
df['playing'] = df['playing'].astype('int')
df['backlogs'] = df['backlogs'].astype('int')
df['wishlist'] = df['wishlist'].astype('int')
df['total_reviews'] = df['total_reviews'].astype('int')
df['total_lists'] = df['total_lists'].astype('int')

In [ ]:
df.head(20)

In [ ]:
df.sort_values(by=['plays'], ascending = False).head(20)

In [ ]:
df.info()

In [ ]:
def remove_hyphens(x):
    if '-' in x:
        x = x.replace('-', '')
        return str(x)

In [ ]:
df['release_date'] = df['release_date'].apply(remove_hyphens)

In [ ]:
df['release_date'].head()

In [ ]:
df['release_date'].sort_values(ascending = False)

In [ ]:
def change_to_datetype(x):
    if x == '00010101':
        return 'null'
    else:
        return datetime.strptime(x, '%Y%m%d').strftime('%m/%d/%Y')

In [ ]:
from datetime import datetime
df['release_date'] = df['release_date'].apply(change_to_datetype)

In [ ]:
df['release_date'].value_counts()['null']

In [ ]:
 df.sort_values(by=['release_date'], ascending = False).head(20)